Update Build SukiSU Ultra OnePlus.yml

diff --git a/.github/workflows/Build SukiSU Ultra OnePlus.yml b/.github/workflows/Build SukiSU Ultra OnePlus.yml
--- a/.github/workflows/Build SukiSU Ultra OnePlus.yml
+++ b/.github/workflows/Build SukiSU Ultra OnePlus.yml
@@ -343,7 +343,19 @@ jobs:
             echo "BUILD.bazel not found!"
             exit 1
           fi
-      
+
+      - name: Fix Bazel syntax in BUILD.bazel
+        run: |
+          cd kernel_workspace/kernel_platform/msm-kernel
+          if [ -f BUILD.bazel ]; then
+            sed -i '755s/,//' BUILD.bazel
+            sed -i '756s/,//' BUILD.bazel
+            sed -i 's/(name = "[^"]*", *\([^,)]*\))/(\1, name = "\2")/g' BUILD.bazel
+          else
+            echo "BUILD.bazel not found!"
+            exit 1
+          fi
+
       - name: Build kernel
         if: ${{ github.event.inputs.CPU == 'sm8650' || github.event.inputs.CPU == 'sm7675' }}
         run: |
